apiVersion: v1
kind: Service
metadata:
  name: cloud-monitoring-app-service
spec:
  selector:
    app: cloud-monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer